### ISSUE TITLE
Do not dump error messages on screen if `xclip` is not available

### ISSUE THREAD

**Issue by ShrykeWindgrace** [goosedb/Monalog#4]
![image](https://github.com/goosedb/Monalog/assets/6421233/e52ad3a9-9a2a-4440-96bd-765dc2f2a77b)

We can can check that this utility is present in `$PATH`. If it is not there, then upon selection of copy method `[Native]` we can show `No 'xclip' found` in the status bar.

**Comment by ShrykeWindgrace** [comment]
Or even better, check this on startup and simply deny the toggle `Osc52 <-> Native` if `xclip` is not found.

**Comment by goosedb** [comment]
I've Implemented dialog on copying error.
